export default {
  login: "Eqillano",
  id: 65677191,
  node_id: "MDQ6VXNlcjY1Njc3MTkx",
  avatar_url: "https://avatars1.githubusercontent.com/u/65677191?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Eqillano",
  html_url: "https://github.com/Eqillano",
  followers_url: "https://api.github.com/users/Eqillano/followers",
  following_url: "https://api.github.com/users/Eqillano/following{/other_user}",
  gists_url: "https://api.github.com/users/Eqillano/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Eqillano/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Eqillano/subscriptions",
  organizations_url: "https://api.github.com/users/Eqillano/orgs",
  repos_url: "https://api.github.com/users/Eqillano/repos",
  events_url: "https://api.github.com/users/Eqillano/events{/privacy}",
  received_events_url: "https://api.github.com/users/Eqillano/received_events",
  type: "User",
  site_admin: false,
  name: "Sergey Vanteev",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 51,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2020-05-20T17:48:25Z",
  updated_at: "2020-07-31T08:33:05Z",
};
